In [1]:
!pip install pyspark faker

Collecting pyspark
  Downloading pyspark-3.5.3.tar.gz (317.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.3/317.3 MB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting faker
  Downloading Faker-30.2.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from faker) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Downloading Faker-30.2.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 63.6 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.3-py2.py3-none-any.whl size=317840625 sha256=af3824a9fb110f070c605d30d7804db793bbb5b536d452d4f423e0034b4e4221
  Stored in directory: /root/.cache/pip/wheels/1b/3a/92/28b93e2fbfdbb07509ca4d6f50c5e407f48dce4ddbda69a4ab
Successfully built pyspark
Installing collected packages: pyspark, faker
Successfully installed faker-30.2.0 pyspark-3.5.3

In [8]:
import pandas as pd
from faker import Faker
import random

# Inicializando Faker
fake = Faker()

# Função para gerar dados fictícios
def generate_data(n):
    data = []  # Corrigido: inicializando a lista
    for _ in range(n):
        name = fake.name()
        age = random.randint(18, 65)
        city = fake.city()
        balance = round(random.uniform(1000, 1000000), 2)
        account_number = fake.bban()

        # Adiciona os dados como uma tupla na lista
        data.append((name, age, city, balance, account_number))

    return data

# Gerar dados para 50.000 registros
dados = generate_data(50000)

# Criar um DataFrame com Pandas
df = pd.DataFrame(dados, columns=['Name', 'Age', 'City', 'Balance', 'Account_Number'])

# Exibir as primeiras linhas do DataFrame
df.head()

             Name  Age               City    Balance      Account_Number
0  Jamie Gonzalez   65         Lake Erica   23495.19  GCLE03467025716308
1       Betty Cox   24      South Heather  756848.59  AWRU96406382533796
2   Kimberly Long   40          East Lisa  300002.14  BJUW48155235043859
3   Joanna Watson   36  North Amandahaven  570795.07  YGNK90519863973719
4   Erin Ellis MD   49      Wilsonborough  581023.61  UPTN11376967741583

In [9]:
df.count()

Name              50000
Age               50000
City              50000
Balance           50000
Account_Number    50000
dtype: int64

In [10]:
# Ordenar os dados pelo saldo ('Balance') em ordem decrescente e limitar a 10 registros
df_ordenado = df.sort_values(by='Balance', ascending=False).head(10)

# Exibir os dados ordenados
df_ordenado

,Name,Age,City,Balance,Account_Number
9268,Allison King,23,North Christopherview,999906.06,WIVT81589899153773
34724,Stephanie Williamson,21,Mcintyreberg,999870.96,IOKO84796365097473
35007,Danielle Sherman,19,Emilyhaven,999860.49,PBLM91301941249919
29799,Keith Gonzalez,53,West Kathleenland,999858.46,GEXN01771417102664
26418,Pamela Powell,28,West Christopherburgh,999833.09,HJJV98549320789076
43426,Madison Wheeler,56,Petersonmouth,999830.98,DFJG89907060834061
15201,Amber Jensen,19,East Tabithashire,999828.36,VMKM05980610274539
46799,Noah Castillo,40,Shannonchester,999818.37,VPMG85035008023221
22820,Jacob Whitney,65,Fosterport,999800.38,HRNY33859668656715
22119,Jesse Brewer,58,Port Lindsayside,999794.96,DXAS00299230388468

In [11]:
# Ordenar os dados pelo saldo ('Balance') em ordem decrescente e limitar a 10 registros
df_ordenado = df.sort_values(by='Balance', ascending=False).head(10)

# Exibir os dados ordenados
df_ordenado

,Name,Age,City,Balance,Account_Number
9268,Allison King,23,North Christopherview,999906.06,WIVT81589899153773
34724,Stephanie Williamson,21,Mcintyreberg,999870.96,IOKO84796365097473
35007,Danielle Sherman,19,Emilyhaven,999860.49,PBLM91301941249919
29799,Keith Gonzalez,53,West Kathleenland,999858.46,GEXN01771417102664
26418,Pamela Powell,28,West Christopherburgh,999833.09,HJJV98549320789076
43426,Madison Wheeler,56,Petersonmouth,999830.98,DFJG89907060834061
15201,Amber Jensen,19,East Tabithashire,999828.36,VMKM05980610274539
46799,Noah Castillo,40,Shannonchester,999818.37,VPMG85035008023221
22820,Jacob Whitney,65,Fosterport,999800.38,HRNY33859668656715
22119,Jesse Brewer,58,Port Lindsayside,999794.96,DXAS00299230388468

In [16]:
# Definir a idade para o filtro
idade = 60

# Filtrar clientes com idade maior que a especificada
df_idade_acima = df[df['Age'] > idade]

# Exibir os 10 primeiros clientes com idade acima do limite
print(df_idade_acima.head(10))

print('-----' * 50)

# Contar o número total de clientes acima da idade especificada
print('Clientes acima de', idade, "=", len(df_idade_acima), 'clientes')

                     Name  Age                 City    Balance  \
0          Jamie Gonzalez   65           Lake Erica   23495.19
7           Gregory Cross   65      East Davidburgh  896625.97
14         Scott Martinez   61           Littleside  200660.52
15           Jacob Fuller   62       East Bryanside  720680.42
30        Stephanie Silva   64      New Darrellfurt  525512.30
51       Michael Gonzalez   63            Ramostown  560654.38
66            Amy Fleming   62     Port Williamberg  547398.86
71          Sharon Gaines   65  West Valerieborough  717944.44
126         Deborah Davis   63         North Adrian  141582.28
133  Miss Barbara Chapman   64         North Pamela  232587.50

         Account_Number
0    GCLE03467025716308
7    NWQA70896692412102
14   PMEF83402807366309
15   JJBQ70498157969719
30   KHWF50822369901553
51   SLQN15438439698000
66   LUVV15237330139000
71   WKAR20198913593492
126  CQLJ15284769270690
133  XRFG77063013830327
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Clientes acima de 60 = 5107 clientes

In [21]:
# Definir os limites de idade e condição para saldo
idade_min = 30
idade_max = 50

# Filtrar clientes com idade entre 30 e 50 anos e idade da conta maior ou igual a 10 anos
df_clientes_filtrados = df.loc[
    (df['Age'] >= idade_min) &
    (df['Age'] <= idade_max)
]

# Ordenar pelo saldo ('Balance') em ordem decrescente
df_clientes_filtrados = df_clientes_filtrados.sort_values(by='Balance', ascending=False)

# Exibir os 10 primeiros clientes com maior saldo dentro da faixa etária
print(df_clientes_filtrados.head(10))

# Exibir o número total de clientes nessa condição
print('-----' * 50)
print()
print('Total de clientes entre', idade_min, 'e', idade_max, 'anos =', len(df_clientes_filtrados), 'clientes')

                    Name  Age               City    Balance  \
46799      Noah Castillo   40     Shannonchester  999818.37
4428       Timothy Smith   31         Larsenfurt  999743.08
11593  Michelle Griffith   38    Lake Shellyside  999741.88
49581   Nichole Martinez   43      Jenniferville  999687.08
22732      Diane Alvarez   38  East Frederickton  999669.86
14555       Andre Tucker   31          Whiteberg  999647.91
39173      Michael Olson   43          Hurstberg  999625.69
39707      Ruth Franklin   40        Briannaview  999573.08
14709        Jeff Watson   45          Laurenton  999569.62
28765      Carolyn Moore   43       East Brandon  999564.35

           Account_Number
46799  VPMG85035008023221
4428   IAIK00800029325560
11593  QMXI53033609705732
49581  JRED24049360454626
22732  ZZIY55828160932658
14555  DHRV15497946476591
39173  HENO39174971283024
39707  MHMX90020201848038
14709  CSWP95068904202468
28765  IWDX13133138520929
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Total de clientes entre 30 e 50 anos = 22053 clientes